project: dot
providers:
  google_secrets_manager:
    kind: google_secretmanager
    maps:
      - id: secrets
        path: projects/vfarcic
        keys:
          github-token: REGISTRY_PASSWORD
          github-user: REGISTRY_USER
          github-registry: REGISTRY_SERVER
          github-email: REGISTRY_EMAIL
