FROM jetpackio/devbox-root-user:latest

WORKDIR /code
COPY devbox.json devbox.json
COPY devbox.lock devbox.lock
COPY gcloud gcloud
RUN devbox run -- echo "Installed Packages."

CMD ["devbox", "shell"]
